In [29]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [30]:
data = pd.DataFrame({
    "resume": [
        "Python developer with machine learning and data analysis skills",
        "Java developer with spring boot and backend experience",
        "Data scientist with Python, deep learning, and NLP",
        "Frontend developer with HTML CSS JavaScript React",
        "Machine learning engineer with Python and AI experience"
    ]
})

data

                                              resume
0  Python developer with machine learning and dat...
1  Java developer with spring boot and backend ex...
2  Data scientist with Python, deep learning, and...
3  Frontend developer with HTML CSS JavaScript React
4  Machine learning engineer with Python and AI e...

In [31]:
job_description = "Looking for a Python developer with machine learning and data science skills"

In [32]:
data['resume'] = data['resume'].str.lower()
vectorizer = TfidfVectorizer()

resume_vectors = vectorizer.fit_transform(data['resume'])
job_vector = vectorizer.transform([job_description])

In [33]:
similarity = cosine_similarity(resume_vectors, job_vector)
data['score'] = similarity

data

                                              resume     score
0  python developer with machine learning and dat...  0.898549
1  java developer with spring boot and backend ex...  0.204148
2  data scientist with python, deep learning, and...  0.452879
3  frontend developer with html css javascript react  0.138505
4  machine learning engineer with python and ai e...  0.469247

In [34]:
ranked_data = data.sort_values(by='score', ascending=False)

print("Top Candidates:\n")
print(ranked_data)

Top Candidates:

                                              resume     score
0  python developer with machine learning and dat...  0.898549
4  machine learning engineer with python and ai e...  0.469247
2  data scientist with python, deep learning, and...  0.452879
1  java developer with spring boot and backend ex...  0.204148
3  frontend developer with html css javascript react  0.138505

In [35]:
required_skills = ["python", "machine learning", "data science"]

def check_skills(resume):
    resume = resume.lower()
    matched = [skill for skill in required_skills if skill in resume]
    missing = [skill for skill in required_skills if skill not in resume]
    return matched, missing

print("\nSkill Analysis:\n")

for i, row in ranked_data.iterrows():
    matched, missing = check_skills(row['resume'])
    print(f"Resume: {row['resume']}")
    print("Matched Skills:", matched)
    print("Missing Skills:", missing)
    print("-"*50)

Skill Analysis:

Resume: python developer with machine learning and data analysis skills
Matched Skills: ['python', 'machine learning']
Missing Skills: ['data science']
--------------------------------------------------
Resume: machine learning engineer with python and ai experience
Matched Skills: ['python', 'machine learning']
Missing Skills: ['data science']
--------------------------------------------------
Resume: data scientist with python, deep learning, and nlp
Matched Skills: ['python']
Missing Skills: ['machine learning', 'data science']
--------------------------------------------------
Resume: java developer with spring boot and backend experience
Matched Skills: []
Missing Skills: ['python', 'machine learning', 'data science']
--------------------------------------------------
Resume: frontend developer with html css javascript react
Matched Skills: []
Missing Skills: ['python', 'machine learning', 'data science']
--------------------------------------------------

In [36]:
print("\nInterpretation:")
print("Candidates with higher matching scores are more suitable for the job role")

Interpretation:
Candidates with higher matching scores are more suitable for the job role

In [38]:
best = ranked_data.iloc[0]

print("\nBest Candidate:")
print("Resume:", best['resume'])
print("Score:", round(best['score'], 3))

Best Candidate:
Resume: python developer with machine learning and data analysis skills
Score: 0.899